artifacts:
- path: out/*.nupkg
  name: NuGet Packages
build_script:
- ps: >-
    Get-ChildItem -Recurse -Filter *.nuspec |% {

        nuget pack $_.FullName -OutputDirectory out

        if (-not $?) {
            exit $LastExitCode
        }
    }
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
test: off
version: '{build}'